// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: analyzer/analyzer.proto

package analyzer

import (
	common "backend-master/internal/api-gen/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeriodBalance struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeriodStart       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	Income            *common.Money          `protobuf:"bytes,3,opt,name=income,proto3" json:"income,omitempty"`
	Expense           *common.Money          `protobuf:"bytes,4,opt,name=expense,proto3" json:"expense,omitempty"`
	Balance           *common.Money          `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CategoryBreakdown []*CategorySpending    `protobuf:"bytes,6,rep,name=category_breakdown,json=categoryBreakdown,proto3" json:"category_breakdown,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeriodBalance) Reset() {
	*x = PeriodBalance{}
	mi := &file_analyzer_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodBalance) ProtoMessage() {}

func (x *PeriodBalance) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodBalance.ProtoReflect.Descriptor instead.
func (*PeriodBalance) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *PeriodBalance) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *PeriodBalance) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *PeriodBalance) GetIncome() *common.Money {
	if x != nil {
		return x.Income
	}
	return nil
}

func (x *PeriodBalance) GetExpense() *common.Money {
	if x != nil {
		return x.Expense
	}
	return nil
}

func (x *PeriodBalance) GetBalance() *common.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *PeriodBalance) GetCategoryBreakdown() []*CategorySpending {
	if x != nil {
		return x.CategoryBreakdown
	}
	return nil
}

type CategorySpending struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TotalAmount   *common.Money          `protobuf:"bytes,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorySpending) Reset() {
	*x = CategorySpending{}
	mi := &file_analyzer_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySpending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySpending) ProtoMessage() {}

func (x *CategorySpending) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySpending.ProtoReflect.Descriptor instead.
func (*CategorySpending) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *CategorySpending) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategorySpending) GetTotalAmount() *common.Money {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

type Forecast struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeriodStart       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	ExpectedIncome    *common.Money          `protobuf:"bytes,3,opt,name=expected_income,json=expectedIncome,proto3" json:"expected_income,omitempty"`
	ExpectedExpense   *common.Money          `protobuf:"bytes,4,opt,name=expected_expense,json=expectedExpense,proto3" json:"expected_expense,omitempty"`
	ExpectedBalance   *common.Money          `protobuf:"bytes,5,opt,name=expected_balance,json=expectedBalance,proto3" json:"expected_balance,omitempty"`
	CategoryBreakdown []*CategorySpending    `protobuf:"bytes,6,rep,name=category_breakdown,json=categoryBreakdown,proto3" json:"category_breakdown,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Forecast) Reset() {
	*x = Forecast{}
	mi := &file_analyzer_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecast) ProtoMessage() {}

func (x *Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecast.ProtoReflect.Descriptor instead.
func (*Forecast) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *Forecast) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *Forecast) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *Forecast) GetExpectedIncome() *common.Money {
	if x != nil {
		return x.ExpectedIncome
	}
	return nil
}

func (x *Forecast) GetExpectedExpense() *common.Money {
	if x != nil {
		return x.ExpectedExpense
	}
	return nil
}

func (x *Forecast) GetExpectedBalance() *common.Money {
	if x != nil {
		return x.ExpectedBalance
	}
	return nil
}

func (x *Forecast) GetCategoryBreakdown() []*CategorySpending {
	if x != nil {
		return x.CategoryBreakdown
	}
	return nil
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	GroupBy       common.TimePeriod      `protobuf:"varint,4,opt,name=group_by,json=groupBy,proto3,enum=common.TimePeriod" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_analyzer_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStatisticsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetStatisticsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetStatisticsRequest) GetGroupBy() common.TimePeriod {
	if x != nil {
		return x.GroupBy
	}
	return common.TimePeriod(0)
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalIncome   *common.Money          `protobuf:"bytes,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense  *common.Money          `protobuf:"bytes,2,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	PeriodData    []*PeriodBalance       `protobuf:"bytes,4,rep,name=period_data,json=periodData,proto3" json:"period_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_analyzer_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatisticsResponse) GetTotalIncome() *common.Money {
	if x != nil {
		return x.TotalIncome
	}
	return nil
}

func (x *GetStatisticsResponse) GetTotalExpense() *common.Money {
	if x != nil {
		return x.TotalExpense
	}
	return nil
}

func (x *GetStatisticsResponse) GetPeriodData() []*PeriodBalance {
	if x != nil {
		return x.PeriodData
	}
	return nil
}

type GetForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Period        common.TimePeriod      `protobuf:"varint,2,opt,name=period,proto3,enum=common.TimePeriod" json:"period,omitempty"`
	PeriodsAhead  int32                  `protobuf:"varint,3,opt,name=periods_ahead,json=periodsAhead,proto3" json:"periods_ahead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastRequest) Reset() {
	*x = GetForecastRequest{}
	mi := &file_analyzer_analyzer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastRequest) ProtoMessage() {}

func (x *GetForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastRequest.ProtoReflect.Descriptor instead.
func (*GetForecastRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{5}
}

func (x *GetForecastRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetForecastRequest) GetPeriod() common.TimePeriod {
	if x != nil {
		return x.Period
	}
	return common.TimePeriod(0)
}

func (x *GetForecastRequest) GetPeriodsAhead() int32 {
	if x != nil {
		return x.PeriodsAhead
	}
	return 0
}

type GetForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forecasts     []*Forecast            `protobuf:"bytes,1,rep,name=forecasts,proto3" json:"forecasts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastResponse) Reset() {
	*x = GetForecastResponse{}
	mi := &file_analyzer_analyzer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastResponse) ProtoMessage() {}

func (x *GetForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastResponse.ProtoReflect.Descriptor instead.
func (*GetForecastResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{6}
}

func (x *GetForecastResponse) GetForecasts() []*Forecast {
	if x != nil {
		return x.Forecasts
	}
	return nil
}

type GetAnomaliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Period        common.TimePeriod      `protobuf:"varint,2,opt,name=period,proto3,enum=common.TimePeriod" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnomaliesRequest) Reset() {
	*x = GetAnomaliesRequest{}
	mi := &file_analyzer_analyzer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnomaliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnomaliesRequest) ProtoMessage() {}

func (x *GetAnomaliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnomaliesRequest.ProtoReflect.Descriptor instead.
func (*GetAnomaliesRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnomaliesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAnomaliesRequest) GetPeriod() common.TimePeriod {
	if x != nil {
		return x.Period
	}
	return common.TimePeriod(0)
}

type GetAnomaliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anomalies     []*CategoryAnomaly     `protobuf:"bytes,1,rep,name=anomalies,proto3" json:"anomalies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnomaliesResponse) Reset() {
	*x = GetAnomaliesResponse{}
	mi := &file_analyzer_analyzer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnomaliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnomaliesResponse) ProtoMessage() {}

func (x *GetAnomaliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnomaliesResponse.ProtoReflect.Descriptor instead.
func (*GetAnomaliesResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{8}
}

func (x *GetAnomaliesResponse) GetAnomalies() []*CategoryAnomaly {
	if x != nil {
		return x.Anomalies
	}
	return nil
}

type CategoryAnomaly struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Mcc             string                 `protobuf:"bytes,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	ActualAmount    *common.Money          `protobuf:"bytes,2,opt,name=actual_amount,json=actualAmount,proto3" json:"actual_amount,omitempty"`
	ExpectedAmount  *common.Money          `protobuf:"bytes,3,opt,name=expected_amount,json=expectedAmount,proto3" json:"expected_amount,omitempty"`
	DeviationAmount *common.Money          `protobuf:"bytes,4,opt,name=deviation_amount,json=deviationAmount,proto3" json:"deviation_amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CategoryAnomaly) Reset() {
	*x = CategoryAnomaly{}
	mi := &file_analyzer_analyzer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryAnomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryAnomaly) ProtoMessage() {}

func (x *CategoryAnomaly) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryAnomaly.ProtoReflect.Descriptor instead.
func (*CategoryAnomaly) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{9}
}

func (x *CategoryAnomaly) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

func (x *CategoryAnomaly) GetActualAmount() *common.Money {
	if x != nil {
		return x.ActualAmount
	}
	return nil
}

func (x *CategoryAnomaly) GetExpectedAmount() *common.Money {
	if x != nil {
		return x.ExpectedAmount
	}
	return nil
}

func (x *CategoryAnomaly) GetDeviationAmount() *common.Money {
	if x != nil {
		return x.DeviationAmount
	}
	return nil
}

type GetUpcomingRecurringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingRecurringRequest) Reset() {
	*x = GetUpcomingRecurringRequest{}
	mi := &file_analyzer_analyzer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingRecurringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingRecurringRequest) ProtoMessage() {}

func (x *GetUpcomingRecurringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingRecurringRequest.ProtoReflect.Descriptor instead.
func (*GetUpcomingRecurringRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{10}
}

func (x *GetUpcomingRecurringRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUpcomingRecurringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*RecurringPayment    `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpcomingRecurringResponse) Reset() {
	*x = GetUpcomingRecurringResponse{}
	mi := &file_analyzer_analyzer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpcomingRecurringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpcomingRecurringResponse) ProtoMessage() {}

func (x *GetUpcomingRecurringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpcomingRecurringResponse.ProtoReflect.Descriptor instead.
func (*GetUpcomingRecurringResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{11}
}

func (x *GetUpcomingRecurringResponse) GetPayments() []*RecurringPayment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type RecurringPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mcc           string                 `protobuf:"bytes,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	TypicalAmount *common.Money          `protobuf:"bytes,2,opt,name=typical_amount,json=typicalAmount,proto3" json:"typical_amount,omitempty"`
	ExpectedDate  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expected_date,json=expectedDate,proto3" json:"expected_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecurringPayment) Reset() {
	*x = RecurringPayment{}
	mi := &file_analyzer_analyzer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecurringPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecurringPayment) ProtoMessage() {}

func (x *RecurringPayment) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecurringPayment.ProtoReflect.Descriptor instead.
func (*RecurringPayment) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{12}
}

func (x *RecurringPayment) GetMcc() string {
	if x != nil {
		return x.Mcc
	}
	return ""
}

func (x *RecurringPayment) GetTypicalAmount() *common.Money {
	if x != nil {
		return x.TypicalAmount
	}
	return nil
}

func (x *RecurringPayment) GetExpectedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpectedDate
	}
	return nil
}

var File_analyzer_analyzer_proto protoreflect.FileDescriptor

const file_analyzer_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x17analyzer/analyzer.proto\x12\banalyzer\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xcd\x02\n" +
	"\rPeriodBalance\x12=\n" +
	"\fperiod_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12%\n" +
	"\x06income\x18\x03 \x01(\v2\r.common.MoneyR\x06income\x12'\n" +
	"\aexpense\x18\x04 \x01(\v2\r.common.MoneyR\aexpense\x12'\n" +
	"\abalance\x18\x05 \x01(\v2\r.common.MoneyR\abalance\x12I\n" +
	"\x12category_breakdown\x18\x06 \x03(\v2\x1a.analyzer.CategorySpendingR\x11categoryBreakdown\"e\n" +
	"\x10CategorySpending\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x120\n" +
	"\ftotal_amount\x18\x02 \x01(\v2\r.common.MoneyR\vtotalAmount\"\xfb\x02\n" +
	"\bForecast\x12=\n" +
	"\fperiod_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x126\n" +
	"\x0fexpected_income\x18\x03 \x01(\v2\r.common.MoneyR\x0eexpectedIncome\x128\n" +
	"\x10expected_expense\x18\x04 \x01(\v2\r.common.MoneyR\x0fexpectedExpense\x128\n" +
	"\x10expected_balance\x18\x05 \x01(\v2\r.common.MoneyR\x0fexpectedBalance\x12I\n" +
	"\x12category_breakdown\x18\x06 \x03(\v2\x1a.analyzer.CategorySpendingR\x11categoryBreakdown\"\xd0\x01\n" +
	"\x14GetStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12-\n" +
	"\bgroup_by\x18\x04 \x01(\x0e2\x12.common.TimePeriodR\agroupBy\"\xb7\x01\n" +
	"\x15GetStatisticsResponse\x120\n" +
	"\ftotal_income\x18\x01 \x01(\v2\r.common.MoneyR\vtotalIncome\x122\n" +
	"\rtotal_expense\x18\x02 \x01(\v2\r.common.MoneyR\ftotalExpense\x128\n" +
	"\vperiod_data\x18\x04 \x03(\v2\x17.analyzer.PeriodBalanceR\n" +
	"periodData\"~\n" +
	"\x12GetForecastRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x06period\x18\x02 \x01(\x0e2\x12.common.TimePeriodR\x06period\x12#\n" +
	"\rperiods_ahead\x18\x03 \x01(\x05R\fperiodsAhead\"G\n" +
	"\x13GetForecastResponse\x120\n" +
	"\tforecasts\x18\x01 \x03(\v2\x12.analyzer.ForecastR\tforecasts\"Z\n" +
	"\x13GetAnomaliesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x06period\x18\x02 \x01(\x0e2\x12.common.TimePeriodR\x06period\"O\n" +
	"\x14GetAnomaliesResponse\x127\n" +
	"\tanomalies\x18\x01 \x03(\v2\x19.analyzer.CategoryAnomalyR\tanomalies\"\xc9\x01\n" +
	"\x0fCategoryAnomaly\x12\x10\n" +
	"\x03mcc\x18\x01 \x01(\tR\x03mcc\x122\n" +
	"\ractual_amount\x18\x02 \x01(\v2\r.common.MoneyR\factualAmount\x126\n" +
	"\x0fexpected_amount\x18\x03 \x01(\v2\r.common.MoneyR\x0eexpectedAmount\x128\n" +
	"\x10deviation_amount\x18\x04 \x01(\v2\r.common.MoneyR\x0fdeviationAmount\"6\n" +
	"\x1bGetUpcomingRecurringRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"V\n" +
	"\x1cGetUpcomingRecurringResponse\x126\n" +
	"\bpayments\x18\x01 \x03(\v2\x1a.analyzer.RecurringPaymentR\bpayments\"\x9b\x01\n" +
	"\x10RecurringPayment\x12\x10\n" +
	"\x03mcc\x18\x01 \x01(\tR\x03mcc\x124\n" +
	"\x0etypical_amount\x18\x02 \x01(\v2\r.common.MoneyR\rtypicalAmount\x12?\n" +
	"\rexpected_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fexpectedDate2\xe5\x02\n" +
	"\x0fAnalyzerService\x12P\n" +
	"\rGetStatistics\x12\x1e.analyzer.GetStatisticsRequest\x1a\x1f.analyzer.GetStatisticsResponse\x12J\n" +
	"\vGetForecast\x12\x1c.analyzer.GetForecastRequest\x1a\x1d.analyzer.GetForecastResponse\x12M\n" +
	"\fGetAnomalies\x12\x1d.analyzer.GetAnomaliesRequest\x1a\x1e.analyzer.GetAnomaliesResponse\x12e\n" +
	"\x14GetUpcomingRecurring\x12%.analyzer.GetUpcomingRecurringRequest\x1a&.analyzer.GetUpcomingRecurringResponseB\x8d\x01\n" +
	"\fcom.analyzerB\rAnalyzerProtoP\x01Z.backend-master/internal/api-gen/proto/analyzer\xa2\x02\x03AXX\xaa\x02\bAnalyzer\xca\x02\bAnalyzer\xe2\x02\x14Analyzer\\GPBMetadata\xea\x02\bAnalyzerb\x06proto3"

var (
	file_analyzer_analyzer_proto_rawDescOnce sync.Once
	file_analyzer_analyzer_proto_rawDescData []byte
)

func file_analyzer_analyzer_proto_rawDescGZIP() []byte {
	file_analyzer_analyzer_proto_rawDescOnce.Do(func() {
		file_analyzer_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyzer_analyzer_proto_rawDesc), len(file_analyzer_analyzer_proto_rawDesc)))
	})
	return file_analyzer_analyzer_proto_rawDescData
}

var file_analyzer_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_analyzer_analyzer_proto_goTypes = []any{
	(*PeriodBalance)(nil),                // 0: analyzer.PeriodBalance
	(*CategorySpending)(nil),             // 1: analyzer.CategorySpending
	(*Forecast)(nil),                     // 2: analyzer.Forecast
	(*GetStatisticsRequest)(nil),         // 3: analyzer.GetStatisticsRequest
	(*GetStatisticsResponse)(nil),        // 4: analyzer.GetStatisticsResponse
	(*GetForecastRequest)(nil),           // 5: analyzer.GetForecastRequest
	(*GetForecastResponse)(nil),          // 6: analyzer.GetForecastResponse
	(*GetAnomaliesRequest)(nil),          // 7: analyzer.GetAnomaliesRequest
	(*GetAnomaliesResponse)(nil),         // 8: analyzer.GetAnomaliesResponse
	(*CategoryAnomaly)(nil),              // 9: analyzer.CategoryAnomaly
	(*GetUpcomingRecurringRequest)(nil),  // 10: analyzer.GetUpcomingRecurringRequest
	(*GetUpcomingRecurringResponse)(nil), // 11: analyzer.GetUpcomingRecurringResponse
	(*RecurringPayment)(nil),             // 12: analyzer.RecurringPayment
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
	(*common.Money)(nil),                 // 14: common.Money
	(common.TimePeriod)(0),               // 15: common.TimePeriod
}
var file_analyzer_analyzer_proto_depIdxs = []int32{
	13, // 0: analyzer.PeriodBalance.period_start:type_name -> google.protobuf.Timestamp
	13, // 1: analyzer.PeriodBalance.period_end:type_name -> google.protobuf.Timestamp
	14, // 2: analyzer.PeriodBalance.income:type_name -> common.Money
	14, // 3: analyzer.PeriodBalance.expense:type_name -> common.Money
	14, // 4: analyzer.PeriodBalance.balance:type_name -> common.Money
	1,  // 5: analyzer.PeriodBalance.category_breakdown:type_name -> analyzer.CategorySpending
	14, // 6: analyzer.CategorySpending.total_amount:type_name -> common.Money
	13, // 7: analyzer.Forecast.period_start:type_name -> google.protobuf.Timestamp
	13, // 8: analyzer.Forecast.period_end:type_name -> google.protobuf.Timestamp
	14, // 9: analyzer.Forecast.expected_income:type_name -> common.Money
	14, // 10: analyzer.Forecast.expected_expense:type_name -> common.Money
	14, // 11: analyzer.Forecast.expected_balance:type_name -> common.Money
	1,  // 12: analyzer.Forecast.category_breakdown:type_name -> analyzer.CategorySpending
	13, // 13: analyzer.GetStatisticsRequest.start_date:type_name -> google.protobuf.Timestamp
	13, // 14: analyzer.GetStatisticsRequest.end_date:type_name -> google.protobuf.Timestamp
	15, // 15: analyzer.GetStatisticsRequest.group_by:type_name -> common.TimePeriod
	14, // 16: analyzer.GetStatisticsResponse.total_income:type_name -> common.Money
	14, // 17: analyzer.GetStatisticsResponse.total_expense:type_name -> common.Money
	0,  // 18: analyzer.GetStatisticsResponse.period_data:type_name -> analyzer.PeriodBalance
	15, // 19: analyzer.GetForecastRequest.period:type_name -> common.TimePeriod
	2,  // 20: analyzer.GetForecastResponse.forecasts:type_name -> analyzer.Forecast
	15, // 21: analyzer.GetAnomaliesRequest.period:type_name -> common.TimePeriod
	9,  // 22: analyzer.GetAnomaliesResponse.anomalies:type_name -> analyzer.CategoryAnomaly
	14, // 23: analyzer.CategoryAnomaly.actual_amount:type_name -> common.Money
	14, // 24: analyzer.CategoryAnomaly.expected_amount:type_name -> common.Money
	14, // 25: analyzer.CategoryAnomaly.deviation_amount:type_name -> common.Money
	12, // 26: analyzer.GetUpcomingRecurringResponse.payments:type_name -> analyzer.RecurringPayment
	14, // 27: analyzer.RecurringPayment.typical_amount:type_name -> common.Money
	13, // 28: analyzer.RecurringPayment.expected_date:type_name -> google.protobuf.Timestamp
	3,  // 29: analyzer.AnalyzerService.GetStatistics:input_type -> analyzer.GetStatisticsRequest
	5,  // 30: analyzer.AnalyzerService.GetForecast:input_type -> analyzer.GetForecastRequest
	7,  // 31: analyzer.AnalyzerService.GetAnomalies:input_type -> analyzer.GetAnomaliesRequest
	10, // 32: analyzer.AnalyzerService.GetUpcomingRecurring:input_type -> analyzer.GetUpcomingRecurringRequest
	4,  // 33: analyzer.AnalyzerService.GetStatistics:output_type -> analyzer.GetStatisticsResponse
	6,  // 34: analyzer.AnalyzerService.GetForecast:output_type -> analyzer.GetForecastResponse
	8,  // 35: analyzer.AnalyzerService.GetAnomalies:output_type -> analyzer.GetAnomaliesResponse
	11, // 36: analyzer.AnalyzerService.GetUpcomingRecurring:output_type -> analyzer.GetUpcomingRecurringResponse
	33, // [33:37] is the sub-list for method output_type
	29, // [29:33] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_analyzer_analyzer_proto_init() }
func file_analyzer_analyzer_proto_init() {
	if File_analyzer_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyzer_analyzer_proto_rawDesc), len(file_analyzer_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analyzer_analyzer_proto_goTypes,
		DependencyIndexes: file_analyzer_analyzer_proto_depIdxs,
		MessageInfos:      file_analyzer_analyzer_proto_msgTypes,
	}.Build()
	File_analyzer_analyzer_proto = out.File
	file_analyzer_analyzer_proto_goTypes = nil
	file_analyzer_analyzer_proto_depIdxs = nil
}
