// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: analyzer/analyzer.proto

package analyzer

import (
	common "backend-master/internal/api-gen/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeriodBalance struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeriodStart       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	Income            *common.Money          `protobuf:"bytes,3,opt,name=income,proto3" json:"income,omitempty"`
	Expense           *common.Money          `protobuf:"bytes,4,opt,name=expense,proto3" json:"expense,omitempty"`
	Balance           *common.Money          `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CategoryBreakdown []*CategorySpending    `protobuf:"bytes,6,rep,name=category_breakdown,json=categoryBreakdown,proto3" json:"category_breakdown,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeriodBalance) Reset() {
	*x = PeriodBalance{}
	mi := &file_analyzer_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodBalance) ProtoMessage() {}

func (x *PeriodBalance) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodBalance.ProtoReflect.Descriptor instead.
func (*PeriodBalance) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *PeriodBalance) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *PeriodBalance) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *PeriodBalance) GetIncome() *common.Money {
	if x != nil {
		return x.Income
	}
	return nil
}

func (x *PeriodBalance) GetExpense() *common.Money {
	if x != nil {
		return x.Expense
	}
	return nil
}

func (x *PeriodBalance) GetBalance() *common.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *PeriodBalance) GetCategoryBreakdown() []*CategorySpending {
	if x != nil {
		return x.CategoryBreakdown
	}
	return nil
}

type CategorySpending struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TotalAmount   *common.Money          `protobuf:"bytes,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorySpending) Reset() {
	*x = CategorySpending{}
	mi := &file_analyzer_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySpending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySpending) ProtoMessage() {}

func (x *CategorySpending) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySpending.ProtoReflect.Descriptor instead.
func (*CategorySpending) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *CategorySpending) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategorySpending) GetTotalAmount() *common.Money {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

type Forecast struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PeriodStart       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	ExpectedIncome    *common.Money          `protobuf:"bytes,3,opt,name=expected_income,json=expectedIncome,proto3" json:"expected_income,omitempty"`
	ExpectedExpense   *common.Money          `protobuf:"bytes,4,opt,name=expected_expense,json=expectedExpense,proto3" json:"expected_expense,omitempty"`
	ExpectedBalance   *common.Money          `protobuf:"bytes,5,opt,name=expected_balance,json=expectedBalance,proto3" json:"expected_balance,omitempty"`
	CategoryBreakdown []*CategorySpending    `protobuf:"bytes,6,rep,name=category_breakdown,json=categoryBreakdown,proto3" json:"category_breakdown,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Forecast) Reset() {
	*x = Forecast{}
	mi := &file_analyzer_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecast) ProtoMessage() {}

func (x *Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecast.ProtoReflect.Descriptor instead.
func (*Forecast) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *Forecast) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *Forecast) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *Forecast) GetExpectedIncome() *common.Money {
	if x != nil {
		return x.ExpectedIncome
	}
	return nil
}

func (x *Forecast) GetExpectedExpense() *common.Money {
	if x != nil {
		return x.ExpectedExpense
	}
	return nil
}

func (x *Forecast) GetExpectedBalance() *common.Money {
	if x != nil {
		return x.ExpectedBalance
	}
	return nil
}

func (x *Forecast) GetCategoryBreakdown() []*CategorySpending {
	if x != nil {
		return x.CategoryBreakdown
	}
	return nil
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	GroupBy       common.TimePeriod      `protobuf:"varint,4,opt,name=group_by,json=groupBy,proto3,enum=common.TimePeriod" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_analyzer_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatisticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStatisticsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetStatisticsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetStatisticsRequest) GetGroupBy() common.TimePeriod {
	if x != nil {
		return x.GroupBy
	}
	return common.TimePeriod(0)
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalIncome   *common.Money          `protobuf:"bytes,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense  *common.Money          `protobuf:"bytes,2,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	PeriodData    []*PeriodBalance       `protobuf:"bytes,4,rep,name=period_data,json=periodData,proto3" json:"period_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_analyzer_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatisticsResponse) GetTotalIncome() *common.Money {
	if x != nil {
		return x.TotalIncome
	}
	return nil
}

func (x *GetStatisticsResponse) GetTotalExpense() *common.Money {
	if x != nil {
		return x.TotalExpense
	}
	return nil
}

func (x *GetStatisticsResponse) GetPeriodData() []*PeriodBalance {
	if x != nil {
		return x.PeriodData
	}
	return nil
}

type GetForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Period        common.TimePeriod      `protobuf:"varint,2,opt,name=period,proto3,enum=common.TimePeriod" json:"period,omitempty"`
	PeriodsAhead  int32                  `protobuf:"varint,3,opt,name=periods_ahead,json=periodsAhead,proto3" json:"periods_ahead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastRequest) Reset() {
	*x = GetForecastRequest{}
	mi := &file_analyzer_analyzer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastRequest) ProtoMessage() {}

func (x *GetForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastRequest.ProtoReflect.Descriptor instead.
func (*GetForecastRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{5}
}

func (x *GetForecastRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetForecastRequest) GetPeriod() common.TimePeriod {
	if x != nil {
		return x.Period
	}
	return common.TimePeriod(0)
}

func (x *GetForecastRequest) GetPeriodsAhead() int32 {
	if x != nil {
		return x.PeriodsAhead
	}
	return 0
}

type GetForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forecasts     []*Forecast            `protobuf:"bytes,1,rep,name=forecasts,proto3" json:"forecasts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastResponse) Reset() {
	*x = GetForecastResponse{}
	mi := &file_analyzer_analyzer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastResponse) ProtoMessage() {}

func (x *GetForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_analyzer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastResponse.ProtoReflect.Descriptor instead.
func (*GetForecastResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_analyzer_proto_rawDescGZIP(), []int{6}
}

func (x *GetForecastResponse) GetForecasts() []*Forecast {
	if x != nil {
		return x.Forecasts
	}
	return nil
}

var File_analyzer_analyzer_proto protoreflect.FileDescriptor

const file_analyzer_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x17analyzer/analyzer.proto\x12\banalyzer\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xcd\x02\n" +
	"\rPeriodBalance\x12=\n" +
	"\fperiod_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12%\n" +
	"\x06income\x18\x03 \x01(\v2\r.common.MoneyR\x06income\x12'\n" +
	"\aexpense\x18\x04 \x01(\v2\r.common.MoneyR\aexpense\x12'\n" +
	"\abalance\x18\x05 \x01(\v2\r.common.MoneyR\abalance\x12I\n" +
	"\x12category_breakdown\x18\x06 \x03(\v2\x1a.analyzer.CategorySpendingR\x11categoryBreakdown\"e\n" +
	"\x10CategorySpending\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x120\n" +
	"\ftotal_amount\x18\x02 \x01(\v2\r.common.MoneyR\vtotalAmount\"\xfb\x02\n" +
	"\bForecast\x12=\n" +
	"\fperiod_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x126\n" +
	"\x0fexpected_income\x18\x03 \x01(\v2\r.common.MoneyR\x0eexpectedIncome\x128\n" +
	"\x10expected_expense\x18\x04 \x01(\v2\r.common.MoneyR\x0fexpectedExpense\x128\n" +
	"\x10expected_balance\x18\x05 \x01(\v2\r.common.MoneyR\x0fexpectedBalance\x12I\n" +
	"\x12category_breakdown\x18\x06 \x03(\v2\x1a.analyzer.CategorySpendingR\x11categoryBreakdown\"\xd0\x01\n" +
	"\x14GetStatisticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12-\n" +
	"\bgroup_by\x18\x04 \x01(\x0e2\x12.common.TimePeriodR\agroupBy\"\xb7\x01\n" +
	"\x15GetStatisticsResponse\x120\n" +
	"\ftotal_income\x18\x01 \x01(\v2\r.common.MoneyR\vtotalIncome\x122\n" +
	"\rtotal_expense\x18\x02 \x01(\v2\r.common.MoneyR\ftotalExpense\x128\n" +
	"\vperiod_data\x18\x04 \x03(\v2\x17.analyzer.PeriodBalanceR\n" +
	"periodData\"~\n" +
	"\x12GetForecastRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x06period\x18\x02 \x01(\x0e2\x12.common.TimePeriodR\x06period\x12#\n" +
	"\rperiods_ahead\x18\x03 \x01(\x05R\fperiodsAhead\"G\n" +
	"\x13GetForecastResponse\x120\n" +
	"\tforecasts\x18\x01 \x03(\v2\x12.analyzer.ForecastR\tforecasts2\xaf\x01\n" +
	"\x0fAnalyzerService\x12P\n" +
	"\rGetStatistics\x12\x1e.analyzer.GetStatisticsRequest\x1a\x1f.analyzer.GetStatisticsResponse\x12J\n" +
	"\vGetForecast\x12\x1c.analyzer.GetForecastRequest\x1a\x1d.analyzer.GetForecastResponseB\x8d\x01\n" +
	"\fcom.analyzerB\rAnalyzerProtoP\x01Z.backend-master/internal/api-gen/proto/analyzer\xa2\x02\x03AXX\xaa\x02\bAnalyzer\xca\x02\bAnalyzer\xe2\x02\x14Analyzer\\GPBMetadata\xea\x02\bAnalyzerb\x06proto3"

var (
	file_analyzer_analyzer_proto_rawDescOnce sync.Once
	file_analyzer_analyzer_proto_rawDescData []byte
)

func file_analyzer_analyzer_proto_rawDescGZIP() []byte {
	file_analyzer_analyzer_proto_rawDescOnce.Do(func() {
		file_analyzer_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyzer_analyzer_proto_rawDesc), len(file_analyzer_analyzer_proto_rawDesc)))
	})
	return file_analyzer_analyzer_proto_rawDescData
}

var file_analyzer_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_analyzer_analyzer_proto_goTypes = []any{
	(*PeriodBalance)(nil),         // 0: analyzer.PeriodBalance
	(*CategorySpending)(nil),      // 1: analyzer.CategorySpending
	(*Forecast)(nil),              // 2: analyzer.Forecast
	(*GetStatisticsRequest)(nil),  // 3: analyzer.GetStatisticsRequest
	(*GetStatisticsResponse)(nil), // 4: analyzer.GetStatisticsResponse
	(*GetForecastRequest)(nil),    // 5: analyzer.GetForecastRequest
	(*GetForecastResponse)(nil),   // 6: analyzer.GetForecastResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*common.Money)(nil),          // 8: common.Money
	(common.TimePeriod)(0),        // 9: common.TimePeriod
}
var file_analyzer_analyzer_proto_depIdxs = []int32{
	7,  // 0: analyzer.PeriodBalance.period_start:type_name -> google.protobuf.Timestamp
	7,  // 1: analyzer.PeriodBalance.period_end:type_name -> google.protobuf.Timestamp
	8,  // 2: analyzer.PeriodBalance.income:type_name -> common.Money
	8,  // 3: analyzer.PeriodBalance.expense:type_name -> common.Money
	8,  // 4: analyzer.PeriodBalance.balance:type_name -> common.Money
	1,  // 5: analyzer.PeriodBalance.category_breakdown:type_name -> analyzer.CategorySpending
	8,  // 6: analyzer.CategorySpending.total_amount:type_name -> common.Money
	7,  // 7: analyzer.Forecast.period_start:type_name -> google.protobuf.Timestamp
	7,  // 8: analyzer.Forecast.period_end:type_name -> google.protobuf.Timestamp
	8,  // 9: analyzer.Forecast.expected_income:type_name -> common.Money
	8,  // 10: analyzer.Forecast.expected_expense:type_name -> common.Money
	8,  // 11: analyzer.Forecast.expected_balance:type_name -> common.Money
	1,  // 12: analyzer.Forecast.category_breakdown:type_name -> analyzer.CategorySpending
	7,  // 13: analyzer.GetStatisticsRequest.start_date:type_name -> google.protobuf.Timestamp
	7,  // 14: analyzer.GetStatisticsRequest.end_date:type_name -> google.protobuf.Timestamp
	9,  // 15: analyzer.GetStatisticsRequest.group_by:type_name -> common.TimePeriod
	8,  // 16: analyzer.GetStatisticsResponse.total_income:type_name -> common.Money
	8,  // 17: analyzer.GetStatisticsResponse.total_expense:type_name -> common.Money
	0,  // 18: analyzer.GetStatisticsResponse.period_data:type_name -> analyzer.PeriodBalance
	9,  // 19: analyzer.GetForecastRequest.period:type_name -> common.TimePeriod
	2,  // 20: analyzer.GetForecastResponse.forecasts:type_name -> analyzer.Forecast
	3,  // 21: analyzer.AnalyzerService.GetStatistics:input_type -> analyzer.GetStatisticsRequest
	5,  // 22: analyzer.AnalyzerService.GetForecast:input_type -> analyzer.GetForecastRequest
	4,  // 23: analyzer.AnalyzerService.GetStatistics:output_type -> analyzer.GetStatisticsResponse
	6,  // 24: analyzer.AnalyzerService.GetForecast:output_type -> analyzer.GetForecastResponse
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_analyzer_analyzer_proto_init() }
func file_analyzer_analyzer_proto_init() {
	if File_analyzer_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyzer_analyzer_proto_rawDesc), len(file_analyzer_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analyzer_analyzer_proto_goTypes,
		DependencyIndexes: file_analyzer_analyzer_proto_depIdxs,
		MessageInfos:      file_analyzer_analyzer_proto_msgTypes,
	}.Build()
	File_analyzer_analyzer_proto = out.File
	file_analyzer_analyzer_proto_goTypes = nil
	file_analyzer_analyzer_proto_depIdxs = nil
}
