// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: master/master.proto

package master

import (
	analyzer "backend-master/internal/api-gen/proto/analyzer"
	common "backend-master/internal/api-gen/proto/common"
	wallet "backend-master/internal/api-gen/proto/wallet"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          common.TransactionType `protobuf:"varint,2,opt,name=type,proto3,enum=common.TransactionType" json:"type,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	FromAccountId string                 `protobuf:"bytes,5,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   string                 `protobuf:"bytes,6,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_master_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTransactionRequest) GetType() common.TransactionType {
	if x != nil {
		return x.Type
	}
	return common.TransactionType(0)
}

func (x *CreateTransactionRequest) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateTransactionRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateTransactionRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *CreateTransactionRequest) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *CreateTransactionRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *wallet.Transaction    `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_master_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetTransaction() *wallet.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_master_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*wallet.Transaction  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_master_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionsResponse) GetTransactions() []*wallet.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_master_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalBalance  *common.Money          `protobuf:"bytes,1,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	Accounts      []*wallet.Account      `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_master_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceResponse) GetTotalBalance() *common.Money {
	if x != nil {
		return x.TotalBalance
	}
	return nil
}

func (x *GetBalanceResponse) GetAccounts() []*wallet.Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsRequest) Reset() {
	*x = GetAnalyticsRequest{}
	mi := &file_master_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsRequest) ProtoMessage() {}

func (x *GetAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{6}
}

func (x *GetAnalyticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAnalyticsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetAnalyticsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetAnalyticsResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Statistics    *analyzer.GetStatisticsResponse `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsResponse) Reset() {
	*x = GetAnalyticsResponse{}
	mi := &file_master_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsResponse) ProtoMessage() {}

func (x *GetAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnalyticsResponse) GetStatistics() *analyzer.GetStatisticsResponse {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type GetForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Period        common.TimePeriod      `protobuf:"varint,2,opt,name=period,proto3,enum=common.TimePeriod" json:"period,omitempty"`
	PeriodsAhead  int32                  `protobuf:"varint,3,opt,name=periods_ahead,json=periodsAhead,proto3" json:"periods_ahead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastRequest) Reset() {
	*x = GetForecastRequest{}
	mi := &file_master_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastRequest) ProtoMessage() {}

func (x *GetForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastRequest.ProtoReflect.Descriptor instead.
func (*GetForecastRequest) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{8}
}

func (x *GetForecastRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetForecastRequest) GetPeriod() common.TimePeriod {
	if x != nil {
		return x.Period
	}
	return common.TimePeriod(0)
}

func (x *GetForecastRequest) GetPeriodsAhead() int32 {
	if x != nil {
		return x.PeriodsAhead
	}
	return 0
}

type GetForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forecasts     []*analyzer.Forecast   `protobuf:"bytes,1,rep,name=forecasts,proto3" json:"forecasts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastResponse) Reset() {
	*x = GetForecastResponse{}
	mi := &file_master_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastResponse) ProtoMessage() {}

func (x *GetForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_master_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastResponse.ProtoReflect.Descriptor instead.
func (*GetForecastResponse) Descriptor() ([]byte, []int) {
	return file_master_master_proto_rawDescGZIP(), []int{9}
}

func (x *GetForecastResponse) GetForecasts() []*analyzer.Forecast {
	if x != nil {
		return x.Forecasts
	}
	return nil
}

var File_master_master_proto protoreflect.FileDescriptor

const file_master_master_proto_rawDesc = "" +
	"\n" +
	"\x13master/master.proto\x12\x06master\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\x1a\x13wallet/wallet.proto\x1a\x17analyzer/analyzer.proto\"\xc6\x02\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.common.TransactionTypeR\x04type\x12%\n" +
	"\x06amount\x18\x03 \x01(\v2\r.common.MoneyR\x06amount\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12&\n" +
	"\x0ffrom_account_id\x18\x05 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x06 \x01(\tR\vtoAccountId\x12.\n" +
	"\x04date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"R\n" +
	"\x19CreateTransactionResponse\x125\n" +
	"\vtransaction\x18\x01 \x01(\v2\x13.wallet.TransactionR\vtransaction\"1\n" +
	"\x16GetTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x17GetTransactionsResponse\x127\n" +
	"\ftransactions\x18\x01 \x03(\v2\x13.wallet.TransactionR\ftransactions\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"u\n" +
	"\x12GetBalanceResponse\x122\n" +
	"\rtotal_balance\x18\x01 \x01(\v2\r.common.MoneyR\ftotalBalance\x12+\n" +
	"\baccounts\x18\x02 \x03(\v2\x0f.wallet.AccountR\baccounts\"\xa0\x01\n" +
	"\x13GetAnalyticsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"W\n" +
	"\x14GetAnalyticsResponse\x12?\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2\x1f.analyzer.GetStatisticsResponseR\n" +
	"statistics\"~\n" +
	"\x12GetForecastRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x06period\x18\x02 \x01(\x0e2\x12.common.TimePeriodR\x06period\x12#\n" +
	"\rperiods_ahead\x18\x03 \x01(\x05R\fperiodsAhead\"G\n" +
	"\x13GetForecastResponse\x120\n" +
	"\tforecasts\x18\x01 \x03(\v2\x12.analyzer.ForecastR\tforecasts2\xa5\x04\n" +
	"\rMasterService\x12r\n" +
	"\x11CreateTransaction\x12 .master.CreateTransactionRequest\x1a!.master.CreateTransactionResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/transactions\x12y\n" +
	"\x0fGetTransactions\x12\x1e.master.GetTransactionsRequest\x1a\x1f.master.GetTransactionsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/users/{user_id}/transactions\x12e\n" +
	"\n" +
	"GetBalance\x12\x19.master.GetBalanceRequest\x1a\x1a.master.GetBalanceResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/users/{user_id}/balance\x12`\n" +
	"\fGetAnalytics\x12\x1b.master.GetAnalyticsRequest\x1a\x1c.master.GetAnalyticsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/analytics\x12\\\n" +
	"\vGetForecast\x12\x1a.master.GetForecastRequest\x1a\x1b.master.GetForecastResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/forecastB\x7f\n" +
	"\n" +
	"com.masterB\vMasterProtoP\x01Z,backend-master/internal/api-gen/proto/master\xa2\x02\x03MXX\xaa\x02\x06Master\xca\x02\x06Master\xe2\x02\x12Master\\GPBMetadata\xea\x02\x06Masterb\x06proto3"

var (
	file_master_master_proto_rawDescOnce sync.Once
	file_master_master_proto_rawDescData []byte
)

func file_master_master_proto_rawDescGZIP() []byte {
	file_master_master_proto_rawDescOnce.Do(func() {
		file_master_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_master_master_proto_rawDesc), len(file_master_master_proto_rawDesc)))
	})
	return file_master_master_proto_rawDescData
}

var file_master_master_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_master_master_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),       // 0: master.CreateTransactionRequest
	(*CreateTransactionResponse)(nil),      // 1: master.CreateTransactionResponse
	(*GetTransactionsRequest)(nil),         // 2: master.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),        // 3: master.GetTransactionsResponse
	(*GetBalanceRequest)(nil),              // 4: master.GetBalanceRequest
	(*GetBalanceResponse)(nil),             // 5: master.GetBalanceResponse
	(*GetAnalyticsRequest)(nil),            // 6: master.GetAnalyticsRequest
	(*GetAnalyticsResponse)(nil),           // 7: master.GetAnalyticsResponse
	(*GetForecastRequest)(nil),             // 8: master.GetForecastRequest
	(*GetForecastResponse)(nil),            // 9: master.GetForecastResponse
	(common.TransactionType)(0),            // 10: common.TransactionType
	(*common.Money)(nil),                   // 11: common.Money
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
	(*wallet.Transaction)(nil),             // 13: wallet.Transaction
	(*wallet.Account)(nil),                 // 14: wallet.Account
	(*analyzer.GetStatisticsResponse)(nil), // 15: analyzer.GetStatisticsResponse
	(common.TimePeriod)(0),                 // 16: common.TimePeriod
	(*analyzer.Forecast)(nil),              // 17: analyzer.Forecast
}
var file_master_master_proto_depIdxs = []int32{
	10, // 0: master.CreateTransactionRequest.type:type_name -> common.TransactionType
	11, // 1: master.CreateTransactionRequest.amount:type_name -> common.Money
	12, // 2: master.CreateTransactionRequest.date:type_name -> google.protobuf.Timestamp
	13, // 3: master.CreateTransactionResponse.transaction:type_name -> wallet.Transaction
	13, // 4: master.GetTransactionsResponse.transactions:type_name -> wallet.Transaction
	11, // 5: master.GetBalanceResponse.total_balance:type_name -> common.Money
	14, // 6: master.GetBalanceResponse.accounts:type_name -> wallet.Account
	12, // 7: master.GetAnalyticsRequest.start_date:type_name -> google.protobuf.Timestamp
	12, // 8: master.GetAnalyticsRequest.end_date:type_name -> google.protobuf.Timestamp
	15, // 9: master.GetAnalyticsResponse.statistics:type_name -> analyzer.GetStatisticsResponse
	16, // 10: master.GetForecastRequest.period:type_name -> common.TimePeriod
	17, // 11: master.GetForecastResponse.forecasts:type_name -> analyzer.Forecast
	0,  // 12: master.MasterService.CreateTransaction:input_type -> master.CreateTransactionRequest
	2,  // 13: master.MasterService.GetTransactions:input_type -> master.GetTransactionsRequest
	4,  // 14: master.MasterService.GetBalance:input_type -> master.GetBalanceRequest
	6,  // 15: master.MasterService.GetAnalytics:input_type -> master.GetAnalyticsRequest
	8,  // 16: master.MasterService.GetForecast:input_type -> master.GetForecastRequest
	1,  // 17: master.MasterService.CreateTransaction:output_type -> master.CreateTransactionResponse
	3,  // 18: master.MasterService.GetTransactions:output_type -> master.GetTransactionsResponse
	5,  // 19: master.MasterService.GetBalance:output_type -> master.GetBalanceResponse
	7,  // 20: master.MasterService.GetAnalytics:output_type -> master.GetAnalyticsResponse
	9,  // 21: master.MasterService.GetForecast:output_type -> master.GetForecastResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_master_master_proto_init() }
func file_master_master_proto_init() {
	if File_master_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_master_master_proto_rawDesc), len(file_master_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_master_master_proto_goTypes,
		DependencyIndexes: file_master_master_proto_depIdxs,
		MessageInfos:      file_master_master_proto_msgTypes,
	}.Build()
	File_master_master_proto = out.File
	file_master_master_proto_goTypes = nil
	file_master_master_proto_depIdxs = nil
}
